# Generated by Django 6.0.4 on 2026-04-17 17:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('especializacion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('edad', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(130)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('DANZA', 'Danza'), ('TEATRO', 'Teatro'), ('MUSICA', 'Música'), ('PINTURA', 'Pintura'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('horario', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('plazas_disponibles', models.PositiveIntegerField()),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='app_gestion_centro_cultural.monitor')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('responsable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sala_responsable', to='app_gestion_centro_cultural.monitor')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadSalaSecundaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_salas_secundarias', to='app_gestion_centro_cultural.actividad')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_actividades_secundarias', to='app_gestion_centro_cultural.sala')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='sala_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_como_sala_principal', to='app_gestion_centro_cultural.sala'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='salas_secundarias',
            field=models.ManyToManyField(blank=True, related_name='actividades_como_sala_secundaria', through='app_gestion_centro_cultural.ActividadSalaSecundaria', to='app_gestion_centro_cultural.sala'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='app_gestion_centro_cultural.actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='app_gestion_centro_cultural.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='actividades', through='app_gestion_centro_cultural.Inscripcion', to='app_gestion_centro_cultural.usuario'),
        ),
        migrations.AddConstraint(
            model_name='actividadsalasecundaria',
            constraint=models.UniqueConstraint(fields=('actividad', 'sala'), name='unique_actividad_sala_secundaria'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('actividad', 'usuario'), name='unique_inscripcion_actividad_usuario'),
        ),
    ]
