# Generated by Django 6.0.4 on 2026-05-12 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_centro_cultural', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="El teléfono debe tener el formato '+num xxx xxx xxx' o 'xxx xxx xxx'.", regex='^(\\+\\d+\\s)?\\d{3}\\s\\d{3}\\s\\d{3}$')]),
        ),
    ]
