# Generated by Django 6.0.4 on 2026-05-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_centro_cultural', '0003_weekly_activity_schedule_and_monitor_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='hora',
            field=models.TimeField(default='09:00'),
        ),
    ]
